"""initial schema

Revision ID: f824dde24477
Revises: 
Create Date: 2025-12-31 11:12:25.542838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f824dde24477'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_external_id'), 'farmers', ['external_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('twilio_message_sid', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='messagedirection'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_twilio_message_sid'), 'messages', ['twilio_message_sid'], unique=True)
    op.create_table('records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('record_type', sa.Enum('SEED_PURCHASE_AND_SOWING', 'HAZARD_EVALUATION', 'CHEMICAL_SPRAY', 'CHEMICAL_PURCHASE', 'CHEMICAL_DISPOSAL', 'POST_HARVEST_CHEMICAL_USAGE', 'FERTILIZER_APPLICATION', 'IRRIGATION', 'SPRAYING_TOOL_SANITATION', 'HARVEST_AND_PACKAGING', 'TRAINING_UPDATE', 'CORRECTION_REPORT', 'UNKNOWN', name='recordtype'), nullable=False),
    sa.Column('occurred_at', sa.Date(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_channel', sa.String(length=50), nullable=False),
    sa.Column('source_input_mode', sa.String(length=20), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('missing_fields', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('needs_followup', sa.Boolean(), nullable=False),
    sa.Column('quality_notes', sa.Text(), nullable=True),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_record_type'), 'records', ['record_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_record_type'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_messages_twilio_message_sid'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_farmers_external_id'), table_name='farmers')
    op.drop_table('farmers')
    # ### end Alembic commands ###
